spring:
  datasource:
    url: jdbc:mysql://your-prod-db-url:3306/your_prod_database_name?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: your_prod_username
    password: ${DB_PROD_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

admin:
  password: ${ADMIN_PASSWORD}

logging:
  file:
    name: /var/log/srr/srr.log

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: "srr"