spring:
  datasource:
    url: jdbc:mysql://localhost:3306/srr_dev_database?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dev_password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

admin:
  password: "dev-password"

logging:
  file:
    name: logs/srr-dev.log

cloud:
  aws:
    credentials:
      access-key: "dev-access-key"
      secret-key: "dev-secret-key"
    s3:
      bucket: "dev-srr"