logging:
  level:
    root: INFO
    com.alstjrzzz.srr: DEBUG
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.name}.%d{yyyy-MM-dd}.%i.gz
      max-file-size: 10MB
      max-history: 60

cloud:
  aws:
    region:
      static: ap-northeast-2 #Seoul
    stack:
      auto: false

